version: "3.1"
services:
  frontend:
    build: app
    image: answer_host
    ports: 
      - "8000:8000"
    networks: 
      - backnet
  redis:
    image: redis:alpine
    networks:
      - backnet    
networks:
  backnet:
    driver: overlay

